import Head from 'next/head'
import styles from '../styles/Home.module.css'
import socket from '../services/socketio';
import { useEffect, useState } from 'react';

export default function Home() {
  const [nickname, setNickname] = useState('');
  const [players, setPlayers] = useState([]);
  const [word, setWord] = useState('');
  const [playerState, setPlayerStatus] = useState({
      givingHints: false,
      guessing: false
  })

  useEffect(() => {
    socket.on('allplayers', data => {
      setPlayers(data);
    });

    socket.on('word', data => {
      setWord(data);
    });
  },[])


  function login(){
    nickname && socket.emit('newPlayer', nickname);
  }

  function startGame(){
    setWord('')
    socket.emit('startGame'); 
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{word}</h1>

        <input 
          value={nickname}
          onChange={(e) => setNickname(e.target.value)}
        />
        <button onClick={() => login()}>Login</button>
        <button onClick={() => startGame()}>Start Game</button>


        <div>
          {
            players &&
            players.map((data, index) => {

              return <p key={index} 
                className={data.givingHints && styles.givingHints || data.guessing && 'guessing' || ''}
              >{data.nickname} - {data.givingHints && 'AQUI'}</p>
            })
          }

        </div>
      </main>

    </div>
  )
}
