import Head from 'next/head';
import { useState} from 'react';
import socket from '../services/socketio';
import styles from '../styles/Home.module.css';
import { Login } from '../components/Login';
import MainGame from '../components/MainGame';

export default function Home() {
  const [nickname, setNickname] = useState('');
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {isLoggedIn ? <MainGame nickname={nickname} /> : (
          <Login 
            nickname={nickname}
            setNickname={setNickname}
            setIsLoggedIn={setIsLoggedIn}
          />
        )}
      </main>
    </div>
  )
}
